### ISSUE TITLE
After last update not working (Meteor 1.2.0.1)

### ISSUE THREAD

**Issue by cosio55** [francocatena/meteor-status#23] opened 2015-09-28 17:10 UTC
Hi, I updated this package using 'meteor update' but now the package is not working, I am receiving this error on console: Uncaught ReferenceError: i18n_status_func is not defined

**Comment by miri-am** [comment] 2015-09-28 20:18
same for me

**Comment by jasonxeno** [comment] 2015-09-29 02:43
Breaks when minified, after typing "meteor --production"

**Comment by sferoze** [comment] 2015-09-29 13:39
yup breaking in production for me too

**Comment by francocatena** [comment] 2015-09-30 18:15
This is a duplicate of #22 if that doesn't fix your issue, please feel free to reopen it.

Cheers.

**Closed by francocatena** 2015-09-30 18:15 UTC
Labels: duplicate
